### ISSUE TITLE
Clean command

### ISSUE THREAD

**Issue by enricobacis** [danhper/fundle#19]
It would be nice to have a `fundle clean` command that removes the directory for plugins that were in the config file but are not there anymore (this is something Vundle also has, so it would be nice to have it also here).

**Comment by danhper** [comment]
Agreed, I am going to add this when I find the time, thank you for the proposal.

**Comment by enricobacis** [comment]
Wonderful, thanks

**Comment by danhper** [comment]
Just published v0.5.0, thank you for your help :smiley:

**Comment by enricobacis** [comment]
You forgot to put the `clean` command it in the `help`

**Comment by danhper** [comment]
@enricobacis Oh, thanks, I completely forgot! Just made a new release with it!
