### ISSUE TITLE
Fundle completions rely on fish-completion-helpers

### ISSUE THREAD

**Issue by brgmnn** [danhper/fundle#2]
The fundle completions rely on your fish-completion-helpers (https://github.com/tuvistavie/fish-completion-helpers) for both `__fish_prog_needs_command` and `__fish_prog_using_command` however they're not mentioned in the readme. Perhaps there should be a section in the readme for the completions mentioning the requirement on fish-completion-helpers?

I personally solved this by just installing fish-completion-helpers with fundle.

**Comment by danhper** [comment]
You are perfectly right, I forgot to mention it.
I just updated the readme, thanks!
