### ISSUE TITLE
Cannot `fundle update`

### ISSUE THREAD

**Issue by hauleth** [danhper/fundle#24]
Output message:

```
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
Updating hauleth/agnoster
Updating fishery/rbenv
Updating fishery/z
```

**Comment by danhper** [comment]
Hi, thanks for reporting.

For some reason, the `.git` directory seems to be missing from some of your plugins.
Just to be sure, could you paste the output of

```
find ~/.config/fish/fundle/ -maxdepth 3 -type d   
```

please?

**Comment by hauleth** [comment]
```
/Users/hauleth/.config/fish/fundle/
/Users/hauleth/.config/fish/fundle//fishery
/Users/hauleth/.config/fish/fundle//fishery/rbenv
/Users/hauleth/.config/fish/fundle//fishery/rbenv/.git
/Users/hauleth/.config/fish/fundle//fishery/rbenv/completions
/Users/hauleth/.config/fish/fundle//fishery/rbenv/conf.d
/Users/hauleth/.config/fish/fundle//fishery/rbenv/functions
/Users/hauleth/.config/fish/fundle//fishery/z
/Users/hauleth/.config/fish/fundle//fishery/z/.git
/Users/hauleth/.config/fish/fundle//fishery/z/conf.d
/Users/hauleth/.config/fish/fundle//fishery/z/functions
/Users/hauleth/.config/fish/fundle//fishery/z/man
/Users/hauleth/.config/fish/fundle//fishery/z/test
/Users/hauleth/.config/fish/fundle//hauleth
/Users/hauleth/.config/fish/fundle//hauleth/agnoster
/Users/hauleth/.config/fish/fundle//hauleth/agnoster/.git
/Users/hauleth/.config/fish/fundle//hauleth/agnoster/agnoster
/Users/hauleth/.config/fish/fundle//hauleth/agnoster/screenshots
```

It seems ok, it looks like fundle do not provide proper `GIT_DIR` when updating.

**Comment by hauleth** [comment]
I think that you should also provide `GIT_WORK_TREE` variable while updating.

**Comment by danhper** [comment]
Yeah, this seems to be fine.

I am setting `git-dir` through the `--git-dir` option, could it be that it gets overriden by an env variable?

I am passing the `work-tree` during the call to checkout, which should be enough.
Any other place you think it should be present?

**Comment by hauleth** [comment]
Ok, I have found the issue. I have overrided `git` with `hub` which do not pass `--git-dir` command to the origin `git`. You should use `command git` instead of bare `git` to be sure that origin git was ran. I will fill issue against `hub` also.

**Comment by danhper** [comment]
@hauleth Thank you for investigating!
I will change to `command git` to be safe, just a moment :smile:

**Comment by danhper** [comment]
I fixed it and updated to 0.5.2, could you run `fundle self-update` and tell me if it works please? :smile:

**Comment by hauleth** [comment]
You forgot to push tag ;)

**Comment by danhper** [comment]
Woops :sweat: 
Here you go! :tada:

**Comment by hauleth** [comment]
Works, thanks.
