### ISSUE TITLE
It's great, but I wanna know how to uninstall it.

### ISSUE THREAD

**Issue by pwwang** [danhper/fundle#26]
I searched around, but found no description about how to uninstall a fish plugin.

**Comment by danhper** [comment]
It's a single file, just remove it :smile:

**Comment by danhper** [comment]
Oh, sorry, do you mean you want to remove a single plugin, or fundle itself? 
If you want to remove a plugin, just remove 

```
fundle plugin 'your-plugin'
```

from your setup and run `fundle clean`.

**Comment by pwwang** [comment]
@tuvistavie sorry, I meant fundle itself. Thanks.

**Comment by danhper** [comment]
In this case, just remove the file

```
rm ~/.config/fish/functions/fundle.fish
```

and don't  forget to remove the fundle related parts from your fish setup!

**Comment by hauleth** [comment]
@tuvistavie maybe `fundle implode` method would be useful?
