### ISSUE TITLE
Compatibility with fisherman/z

### ISSUE THREAD

**Issue by christianrondeau** [danhper/fundle#29]
Hi! I've been trying fundle (commit `e3afe719`, version `0.5.3`) and tried installing `fisherman/z` (the os is termux) without success. 

I fiddled a little bit and I believe the problem is that `init.fish` is sourced, otherwise all `.fish` files in the root folder of the plug-in, but this one requires sourcing `conf.d/*.fish`. 

    source ~/.config/fish/fundle/fisherman/z/conf.d/z.fish

Is this something that is expected to work? Something like this would work :

    for file in ~/.config/fish/fundle/... /conf.d/*.fish
      source $file
    end

Let me know what you think!

**Comment by danhper** [comment]
Hi, very sorry for the delay.
Indeed, fisherman started the conf.d convention after I wrote fundle. I would not mind sourcing everything in conf.d if it can help.
A PR would be very welcome if you have time.
Thank you.
