### ISSUE TITLE
Warning about '' being invalid integer in test

### ISSUE THREAD

**Issue by zimme** [danhper/fundle#32]
In `__fundle_compare_versions` there's a chance that `$v1` or `$v2` is empty which creates warnings with the `-lt`/`-gt` comparisons as an empty value isn't a valid integer.

I see that you check for the case when one is present and the other one isn't. However I don't know how to change the code so that it only does the `-lt`/`-gt` checks when both values are present.

**Comment by zimme** [comment]
I'm seeing this when running `fundle self-update`.

**Comment by danhper** [comment]
Thanks for reporting, this should now be fixed.
