### ISSUE TITLE
Could not update plugin

### ISSUE THREAD

**Issue by BarbzYHOOL** [danhper/fundle#41]
I have one of my plugin (a theme in fact) in my computer and not on a distant repo
`fundle plugin 'user/yhool_fish' --url "/home/user/PROGRAMS/FISH/yhool_fish"`

When I `fundle update` :
Could not update xxx/xxx

But I don't know what the issue is, I can't find it :(

How can I debug this?

Note: I have other plugins installed this way and no problem

**Comment by danhper** [comment]
Hi!
Sorry, there is not a decent debug option for now. The easiest thing to do is to change the code to actually output the error (maybe we should output errors by default).
I think for you the command on line 89 (git rev-parse) is failing so you could remove the 2>/dev/null at the end to see what's happening.
Sorry for the trouble.

**Comment by BarbzYHOOL** [comment]
Oh yes, please update it. Maybe remove all `2>/dev/null` ?

My mistake was simple: I had symlinked the themes' files but it wasn't a git repo, so it failed. Instead i symlinked my git repo and it works fine now!

Thank you!

**Comment by BarbzYHOOL** [comment]
@danhper ok in fact it didn't work lol

I can't symlink my git repo, I need to copy it. Any idea why?

**Comment by BarbzYHOOL** [comment]
My bad, I needed to "fundle install"

And I guess I understand why I can't symlink + "fundle update", it's because it uses git
