### ISSUE TITLE
fundle update asks for my password on github also no SSH remote

### ISSUE THREAD

**Issue by BarbzYHOOL** [danhper/fundle#43]
@danhper 
When I `fundle update`, it iterates through my plugin list, and when it reaches:

> fundle plugin BarbzYHOOL/plugin-bak

It asks me for my github password. But why?? look it is available here https://github.com/BarbzYHOOL/plugin-bak it's not private

Also, why it doesn't use my SSH key instead? Is it possible to select my SSH key to use with fundle for github, gitlab etc?

**Comment by danhper** [comment]
This is very weird, it uses the https git endpoint by default so if the repository is public this should not happen. Maybe try to go to `~/.config/fish/fundle/BarbzYHOOL/plugin-bak` and check what the remote looks like with `git remote show origin`.
You can use any git repository and any protocol, just add `--url REPO_URL` to `fundle plugin `: e.g.

```fish
fundle plugin 'BarbzYHOOL/plugin-bak' --url 'git@github.com:BarbzYHOOL/plugin-bak.git'
```

**Comment by BarbzYHOOL** [comment]
`https://github.com/BarbzYHOOL/plugin-bak.git` is my remote
and in my config (/etc/fish/conf.d/fundle_plugins.fish) there is this `fundle plugin BarbzYHOOL/plugin-bak`

```
git remote show origin                                                                                                             15ms|23:09:21
* remote origin
  Fetch URL: https://github.com/BarbzYHOOL/plugin-bak.git
  Push  URL: https://github.com/BarbzYHOOL/plugin-bak.git
  HEAD branch: master
  Remote branches:
    master  tracked
    patch-1 tracked
  Local branch configured for 'git pull':
    master merges with remote master
  Local ref configured for 'git push':
    master pushes to master (local out of date)

```

Ok ty for SSH, I think I had found this before but forgot it :P

**Comment by BarbzYHOOL** [comment]
Ok so in fact my error came from anything after this line:

fundle plugin fisherman/tio


So i went to fisherman/tio

and there is nothing, in fact the whole fisherman repo has disappeared...
