### ISSUE TITLE
Rerun nightly tests?

### ISSUE THREAD

**Issue by faho** [danhper/fundle#44]
Hi,

as you might have noticed, the nightly tests on Travis have been failing for a while, but https://github.com/fish-shell/fish-shell/commit/a1c481c06aa187b741c5b4db22ae0629e949832d should have fixed it.

So if you could click the "retry test" button on https://travis-ci.org/danhper/fundle, we could see if it's working.

**Comment by danhper** [comment]
Hi, it now seems to pass again, thanks!
