### ISSUE TITLE
This plugin doesn't work with fundle (i guess), but why?

### ISSUE THREAD

**Issue by BarbzYHOOL** [danhper/fundle#45]
Do you have any idea why https://github.com/BarbzYHOOL/plugin-pyenv the init.fish is not loaded?

you can verify by installing the plugin, then you QUIT the terminal and open another one, then run `echo $PYENV_ROOT` and see, it's not set while the init.fish sets it up (in fact nothing is read from the init.fish)

**Comment by danhper** [comment]
`init.fish` is executed but you create `PYENV_ROOT` as a local variable so it is only defined in the current file.
Just replace `set -l` by `set -xg` and it should work.

**Comment by BarbzYHOOL** [comment]
I have completely removed everything in init.fish and replaced by something else and it didn't execute/load at all so I don't think this is related :'(

(i have put "abbr -a te test" for example and it didn't work)

Edit: yes i retried to be sure, doesn't change anything

**Comment by danhper** [comment]
I tried with the repository you gave me and it worked perfectly fine. Is there any chance you could create a Dockerfile which reproduces the issue please?

**Comment by BarbzYHOOL** [comment]
sorry was a mistake from me, I didn't realize I needed to put "fundle init" in ALL the conf.fish (/etc/fish and ~/config/fish)
