### ISSUE TITLE
Use fishtape for tests?

### ISSUE THREAD

**Issue by ghost** [danhper/fundle#5]
What do you think about porting your tests to [Fishtape](https://github.com/fisherman/fishtape/)?

**Comment by danhper** [comment]
Hi, thanks for the proposal.

Actually I would love to have an easier and more systematic way of testing at least fundle packages in general, as most packages are not tested.

So I think integrating a test framework for fundle itself, and to test fundle packages could be nice.
It could make it quite easy to have a `fundle test` command or something like this.

Do you think it would be possible to have fishtape installed with fundle?
I would love to be able to write

``` fish
fundle plugin 'fisherman/fishtape'
fundle init
fundle install

fishtape path/to/tests/*.fish
```

in my tests, without having to worry more about installation.

**Comment by ghost** [comment]
Fishtape is framework agnostic. So, yes, you could install it as a fundle plugin (or omf, or wahoo, or whatever). 

Fishtape installs `fishtape.fish` into `~/.config/fish/functions/fishtape.fish` and also creates a directory inside `~/.config/fish/fishtape` to store the runtime which is injected into the compiled fish code when test files are run.

**Comment by danhper** [comment]
@bucaran Seems to be working nice!

**Comment by ghost** [comment]
Now just for fun:

```
npm install tap-nyan
```

and pipe fishtape TAP stream to get

![](https://camo.githubusercontent.com/e9f949b2a166d8d793f1055b3cf7badc62109b34/687474703a2f2f692e696d6775722e636f6d2f543165483135362e706e67) 

for free.

**Comment by danhper** [comment]
Yeah, I saw there are plenty of cool consumers for tap! :smile:

**Comment by bucaran** [comment]
:+1:
