### ISSUE TITLE
Update single plugin

### ISSUE THREAD

**Issue by hunter-richardson** [danhper/fundle#51]
Is there a way to ask `fundle update` to pull only a specific plugin? I'm trying to implement a script that pulls installed plugins in random order:
```fish
for i in (fundle list --short | shuf)
  fundle update $i
end
```
...but `fundle update` pulls the whole list.

**Comment by BarbzYHOOL** [comment]
I don't think so at the moment :(

**Comment by danhper** [comment]
Hi, there currently isn't but a PR would be very welcome. Thanks!

**Comment by hunter-richardson** [comment]
My apologies; I'm kind of new at this.
The [new PR](https://github.com/danhper/fundle/pull/new/master) link asks me to compare branches, but I'm not a collaborator to your repo, so I can't create a new branch.

**Comment by BarbzYHOOL** [comment]
You need to fork the repo and edit it, then you open up https://github.com/danhper/fundle/ and a javascript message will appear in yellow that you can click to open the PR easily


To try this out, select a file in https://github.com/danhper/fundle/ and click on the pencil icon to edit it, github will tell you it has automatically forked the repo and you are editing your own fork directly on github (not practical)

**Comment by hunter-richardson** [comment]
My [PR](https://github.com/hunter-richardson/fundle) implements a fairly simple modification to [functions/fundle.fish](https://github.com/danhper/fundle/functions/fundle.fish).

Running `fundle update $plugin` where `$plugin` is one of the names from `fundle list --short` will pull down only that plugin; running `fundle update $plugin` where `$plugin` is **NOT** one of the names from `fundle list --short` will show an error message and pull down the list as normal; running `fundle update` will also pull down the list as normal.

**Comment by hunter-richardson** [comment]
My [PR](https://github.com/hunter-richardson/fundle) implements a fairly simple modification to [functions/fundle.fish](functions/fundle.fish).

Running `fundle update $plugin` with `$plugin` one of the names in `fundle list --short` will pull down only that plugin; running `fundle update $plugin` with `$plugin` **NOT** one of the names in `fundle list --short` will display an error message and pull down the full list; running `fundle update` will pull down the full list as normal.

**Comment by hunter-richardson** [comment]
See #52 .

**Comment by hunter-richardson** [comment]
My fork was merged and deleted. This issue can now be closed.
