### ISSUE TITLE
"Could not checkout revision", plugins don't work

### ISSUE THREAD

**Issue by bandithedoge** [danhper/fundle#53]
![image](https://user-images.githubusercontent.com/26331682/103439969-2b1ff800-4c42-11eb-82c5-27bb979f49c7.png)

Whenever I run `fundle update`, I get this error. The plugins' functions work, but everything else doesn't. For example, I can run `__fzf_search_current_dir` but the Ctrl+F keybinding does nothing. Same with the auto pairs - they just don't work.

**Comment by danhper** [comment]
Hi @bandithedoge, thanks for the report.
The code was wrongly assuming that all repos have a branch named master, so it was failing for repos using a `main` branch instead.
I just fixed that and pushed a new version (0.7.1), please let me know if you run into any issue.

@jorgebucaran Cool stuff, I also installed it, thanks for that! https://github.com/jorgebucaran/autopair.fish
